'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { ArrowUpRight, BarChart3, Bell, Globe2, Menu, Search, TrendingUp, X } from 'lucide-react'

const fallbackStories = [
  { id: 'preview-1', category: 'Markets', tag: 'MARKET MOVING', title: 'Infera is connecting the signals behind business and market news', sourceName: 'Infera Intelligence Desk', publishedAt: new Date().toISOString(), trendScore: 94, description: 'Live stories will appear here as the news intelligence engine connects to trusted sources.' },
  { id: 'preview-2', category: 'Business', tag: 'BUSINESS', title: 'Business signals are being filtered for relevance, momentum and impact', sourceName: 'Infera Business Desk', publishedAt: new Date().toISOString(), trendScore: 89, description: 'Infera is designed to separate important developments from the daily noise.' },
  { id: 'preview-3', category: 'Trends', tag: 'RISING TREND', title: 'Emerging trends will be tracked before they become mainstream', sourceName: 'Infera Trends Lab', publishedAt: new Date().toISOString(), trendScore: 87, description: 'The trend engine will combine recency, story volume and relevance to identify rising signals.' },
  { id: 'preview-4', category: 'Entertainment', tag: 'CULTURE', title: 'Entertainment signals will bring global and African culture into one view', sourceName: 'Infera Culture Desk', publishedAt: new Date().toISOString(), trendScore: 82, description: 'Movies, music, streaming and cultural stories will be tracked alongside business and market intelligence.' },
]
const movers = [['AI agents', 'Technology', 96], ['African fintech', 'Business', 91], ['Gold', 'Markets', 88], ['Streaming', 'Entertainment', 84], ['Digital assets', 'Markets', 81]]
function relativeTime(date) { const seconds = Math.max(1, Math.floor((Date.now() - new Date(date).getTime()) / 1000)); if (seconds < 60) return `${seconds}s ago`; if (seconds < 3600) return `${Math.floor(seconds / 60)}m ago`; if (seconds < 86400) return `${Math.floor(seconds / 3600)}h ago`; return `${Math.floor(seconds / 86400)}d ago` }
export default function Home() {
  const [category, setCategory] = useState('All'), [search, setSearch] = useState(''), [menu, setMenu] = useState(false), [stories, setStories] = useState(fallbackStories), [live, setLive] = useState(false)
  useEffect(() => { fetch('/api/news').then(r => r.ok ? r.json() : Promise.reject()).then(d => { if (d.stories?.length) setStories(d.stories); setLive(true) }).catch(() => setLive(false)) }, [])
  const filtered = useMemo(() => stories.filter(s => (category === 'All' || s.category?.toLowerCase() === category.toLowerCase()) && `${s.title} ${s.description || ''} ${s.summary || ''} ${s.sourceName || ''}`.toLowerCase().includes(search.toLowerCase())), [category, search, stories])
  const categories = ['All', 'Business', 'Markets', 'Trends', 'Entertainment']
  return <main>
    <header className="topbar"><div className="nav inner"><button className="mobileMenu" onClick={() => setMenu(!menu)} aria-label="Menu">{menu ? <X/> : <Menu/>}</button><Link className="brand" href="/"><span>I</span> INFERA</Link><nav className={menu ? 'open' : ''}>{categories.slice(1).map(c => <button key={c} onClick={() => { setCategory(c); setMenu(false) }}>{c}</button>)}<button onClick={() => { setCategory('All'); setMenu(false) }}>AFRICA</button></nav><div className="navActions"><button className="iconBtn"><Bell size={18}/></button><button className="subscribe">Get the Brief</button></div></div></header>
    <section className="hero inner"><div className="heroCopy"><div className="eyebrow"><span className="liveDot"/> {live ? 'LIVE INTELLIGENCE' : 'INTELLIGENCE PREVIEW'}</div><h1>Know what happened.<br/><em>Understand what matters.</em></h1><p>Infera brings business, markets, trends and entertainment into one intelligent daily view — with the context behind the headline.</p><div className="heroButtons"><button className="primary" onClick={() => document.getElementById('feed').scrollIntoView({ behavior: 'smooth' })}>Explore today's signals <ArrowUpRight size={18}/></button><button className="secondary" onClick={() => document.getElementById('why').scrollIntoView({ behavior: 'smooth' })}>How Infera works</button></div></div><div className="signalCard"><div className="cardTop"><span>GLOBAL SIGNAL</span><span>{live ? 'LIVE' : 'PREVIEW'}</span></div><div className="signalNumber">87<span>/100</span></div><h3>Market & business momentum</h3><div className="meter"><i style={{ width: '87%' }}/></div><div className="signalRows"><div><b>Business</b><span>↑ 12%</span></div><div><b>Markets</b><span>↑ 8%</span></div><div><b>Trends</b><span>↑ 17%</span></div></div></div></section>
    <section className="ticker"><div className="tickerInner"><strong>WHAT'S MOVING</strong>{movers.map(([name, type, score]) => <span key={name}><b>{name}</b> {type} <i>{score}</i></span>)}</div></section>
    <section className="inner content" id="feed"><div className="sectionHead"><div><div className="eyebrow">THE INFERA FEED</div><h2>Top intelligence</h2></div><div className="search"><Search size={17}/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search Infera"/></div></div><div className="tabs">{categories.map(c => <button className={category === c ? 'active' : ''} key={c} onClick={() => setCategory(c)}>{c}</button>)}</div><div className="grid">{filtered.map((story, i) => <article className={i === 0 ? 'story featured' : 'story'} key={story.id || story.url}><div className="storyVisual"><span>{story.category}</span><div className="visualGlyph">{['markets','business'].includes(story.category?.toLowerCase()) ? <BarChart3/> : story.category?.toLowerCase() === 'trends' ? <TrendingUp/> : story.category?.toLowerCase() === 'africa' ? <Globe2/> : <span>✦</span>}</div></div><div className="storyBody"><div className="storyMeta"><span>{story.tag || story.category?.toUpperCase()}</span><span>{relativeTime(story.publishedAt)}</span></div><h3>{story.title}</h3><p>{story.summary || story.description || 'Infera is analyzing this story for context and relevance.'}</p><div className="storyFooter"><span>{story.sourceName || 'Infera Intelligence Desk'}</span><strong>{Math.round(story.momentumScore || story.trendScore || 0)} <small>signal</small></strong></div>{!String(story.id).startsWith('preview-') && story.id && <Link className="storyLink" href={`/story/${story.id}`}>Read intelligence <ArrowUpRight size={14}/></Link>}</div></article>)}</div>{!filtered.length && <div className="empty">No stories match your search.</div>}</section>
    <section className="why" id="why"><div className="inner whyGrid"><div><div className="eyebrow">THE INFERA DIFFERENCE</div><h2>Headlines tell you <em>what.</em><br/>Infera explains <em>why.</em></h2></div><div className="whyText"><p>Every major story is designed to answer the questions that matter: what happened, why it matters, what could change next, and which signals deserve attention.</p><div className="featureList"><span><b>01</b> Source-aware reporting</span><span><b>02</b> AI-assisted context</span><span><b>03</b> Momentum & trend scoring</span><span><b>04</b> Africa + global perspective</span></div></div></div></section>
    <footer><div className="inner footerGrid"><div><Link className="brand" href="/"><span>I</span> INFERA</Link><p>News, signals and intelligence for a faster world.</p></div><div><b>Explore</b><a href="#feed">Business</a><a href="#feed">Markets</a><a href="#feed">Trends</a><a href="#feed">Entertainment</a></div><div><b>Platform</b><a href="#why">About</a><a href="#why">Methodology</a><a href="#">Contact</a><a href="#">Newsletter</a></div></div><div className="inner copyright">© 2026 Infera. Intelligence, not noise.</div></footer>
  </main>
}
