'use client'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, ArrowUpRight, ExternalLink, Globe2, TrendingUp } from 'lucide-react'

export default function StoryPage({ params }) {
  const [story, setStory] = useState(null)
  const [loading, setLoading] = useState(true)
  useEffect(() => {
    fetch('/api/intelligence').then(r => r.json()).then(data => setStory((data.signals || []).find(item => String(item.id) === String(params.id)))).catch(() => {}).finally(() => setLoading(false))
  }, [params.id])
  if (loading) return <main className="storyPage"><div className="inner pageState">Loading intelligence…</div></main>
  if (!story) return <main className="storyPage"><div className="inner pageState"><Link href="/" className="back"><ArrowLeft size={16}/> Back to Infera</Link><h1>Story not found</h1><p>This intelligence item may have expired from the live feed.</p></div></main>
  const entities = story.entities || []
  return <main className="storyPage"><header className="topbar"><div className="nav inner"><Link href="/" className="brand"><span>I</span> INFERA</Link><div className="navSpacer"/><Link href="/" className="back"><ArrowLeft size={15}/> Feed</Link></div></header><article className="inner intelligenceArticle"><div className="articleKicker"><span>{story.category}</span><span>{story.tag || 'INTELLIGENCE'}</span><span>{story.publishedAt ? new Date(story.publishedAt).toLocaleString() : 'Just now'}</span></div><h1>{story.title}</h1><p className="dek">{story.summary || story.description || 'Infera intelligence analysis for this developing story.'}</p><div className="articleLayout"><div className="analysis"><section><div className="label">WHAT HAPPENED</div><p>{story.summary || story.description || 'This story is being monitored as new information develops.'}</p></section><section className="highlight"><div className="label">WHY IT MATTERS</div><h2>{story.whyItMatters || 'The significance of this development is still being assessed.'}</h2></section><section><div className="label">WHAT TO WATCH</div><p>{story.whatToWatch || 'Watch for follow-up reporting, official announcements, market reactions and new facts that could change the signal.'}</p></section><section><div className="label">SOURCE</div><p>{story.sourceName || 'Infera Intelligence Desk'}</p>{story.url && <a className="sourceLink" href={story.url} target="_blank" rel="noreferrer">Read original report <ExternalLink size={14}/></a>}</section></div><aside className="metrics"><div className="metricCard dark"><span>INFERA SIGNAL</span><strong>{Math.round(story.momentumScore || story.trendScore || 0)}<small>/100</small></strong><p>Momentum</p><div className="metricBar"><i style={{width:`${Math.min(100, story.momentumScore || story.trendScore || 0)}%`}}/></div></div><div className="metricGrid"><div><span>Importance</span><b>{story.importanceScore || 0}</b></div><div><span>Market</span><b>{story.marketRelevance || 0}</b></div><div><span>Africa</span><b>{story.africaRelevance || 0}</b></div><div><span>Sentiment</span><b>{story.sentiment || 'neutral'}</b></div></div><div className="entityCard"><div className="label">SIGNALS & ENTITIES</div>{entities.length ? entities.map((e,i)=><span className="entity" key={i}><Globe2 size={12}/>{typeof e === 'string' ? e : e.name}</span>) : <p>No entities extracted yet.</p>}</div></aside></div><div className="articleBottom"><TrendingUp size={18}/><span>Signal scores update as new coverage arrives.</span><Link href="/">Explore more intelligence <ArrowUpRight size={15}/></Link></div></article></main>
}
